### ISSUE TITLE
Set Water Density?

### ISSUE THREAD

**Issue by E3t1jump** [ControlEverythingCommunity/MS5837-30BA01#1]
Is there a way to set the water density (997 for fresh water)? As best I can tell this is hard set for salt water density.

We are using the Python code with RaspPi.

**Comment by ryker1990** [comment]
This is a pressure and humidity sensor. what are you trying to achieve . Please elaborate.

**Comment by E3t1jump** [comment]
We are trying to determine the depth of our ROV in either fresh or salt
water. We have used this same sensor with Arduino and the Arduino library
has a value to adjust for the different densities between fresh and salt
water but we find no such input value in your RaspberyPi code. Our
understanding is this is a pressure and temperature sensor and the
temperature values we get from the sensor through your code is accurate,
but the pressure is out of scale for sub surface readings.
